#cloud-config

# sets the hostname to 'terraformed'
hostname: terraformed

ssh_authorized_keys:
- ${ssh_pub_key}

write_files:
- path: /etc/netplan/10-user-network.yaml
  content: |
    network:
      version: 2
      ethernets:
        ens192:
          dhcp4: false #true to use dhcp
          addresses:
          - ${ip}
          gateway4: ${gw} # Set gw here
          nameservers:
            addresses:
            - ${dns} # Set DNS ip address here

runcmd:
  - netplan apply
  - sleep 5
  - ifconfig -a
  - route -n